project:
  type: website

website:
  title: "TDF2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: etappes.qmd
        text: Etapes
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




